'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("HotelBooking.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vui lòng nhập tên đăng nhập.
        '''</summary>
        Friend ReadOnly Property LOGIN_M001() As String
            Get
                Return ResourceManager.GetString("LOGIN_M001", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vui lòng nhập mật khẩu.
        '''</summary>
        Friend ReadOnly Property LOGIN_M002() As String
            Get
                Return ResourceManager.GetString("LOGIN_M002", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tài khoản không tồn tại.
        '''</summary>
        Friend ReadOnly Property LOGIN_M003() As String
            Get
                Return ResourceManager.GetString("LOGIN_M003", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mật khẩu không đúng.
        '''</summary>
        Friend ReadOnly Property LOGIN_M004() As String
            Get
                Return ResourceManager.GetString("LOGIN_M004", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vui lòng nhập tên đăng nhập.
        '''</summary>
        Friend ReadOnly Property SIGNUP_M001() As String
            Get
                Return ResourceManager.GetString("SIGNUP_M001", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vui lòng nhập địa chỉ Email.
        '''</summary>
        Friend ReadOnly Property SIGNUP_M002() As String
            Get
                Return ResourceManager.GetString("SIGNUP_M002", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vui lòng nhập lại địa chỉ Email.
        '''</summary>
        Friend ReadOnly Property SIGNUP_M003() As String
            Get
                Return ResourceManager.GetString("SIGNUP_M003", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vui lòng nhập mật khẩu.
        '''</summary>
        Friend ReadOnly Property SIGNUP_M004() As String
            Get
                Return ResourceManager.GetString("SIGNUP_M004", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vui lòng nhập lại mật khẩu.
        '''</summary>
        Friend ReadOnly Property SIGNUP_M005() As String
            Get
                Return ResourceManager.GetString("SIGNUP_M005", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tên đăng nhập đã tồn tại.
        '''</summary>
        Friend ReadOnly Property SIGNUP_M006() As String
            Get
                Return ResourceManager.GetString("SIGNUP_M006", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Địa chỉ Email đã tồn tại.
        '''</summary>
        Friend ReadOnly Property SIGNUP_M007() As String
            Get
                Return ResourceManager.GetString("SIGNUP_M007", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
